// Tickers with a logo in this folder (file name = Yahoo ticker, or the broker symbol
// when there's no Yahoo ticker). Regenerated by scripts/stock_logo.py.
window.NET_STOCK_LOGOS = ["1155.KL", "9618.HK", "9988.HK", "AAPL", "AMZN", "CPRT", "ELV", "GOOG", "LULU", "MBGL", "META", "MSFT", "SAMSUNGCDGN", "SPGI", "SPY", "U11.SI", "VOO"];
